language: rust

env:
  global:
    - TARGET_ARCH=x86_64
    - TARGET_VENDOR=-unknown
    - TARGET_OS=linux-gnu

rust:
  - stable
  - beta
  - nightly

matrix:
  include:
    - rust: nightly
      env: FEATURES=nightly

script:
  - ci/script.sh

after_success:
  - ci/travis-doc-upload.sh
