[package]
name = "hash-roll"
version = "0.1.0"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "A selection of rolling hashes"
keywords = [ "hash", "rolling", "incremental", "split" ]

[features]

# Enable things that require nightly rust (benchmarks)
nightly = []

[dev-dependencies]
rand = "*.0"
