[package]
name = "hash-roll"
version = "0.1.1"
authors = ["Cody P Schafer <dev@codyps.com>"]
description = "A selection of rolling hashes"
keywords = [ "hash", "rolling", "incremental", "split" ]
license = "AGPL-3.0"
repository = "https://github.com/jmesmon/hash-roll.git"
documentation = "https://docs.rs/hash-roll"

[features]
# Enable things that require nightly rust (benchmarks)
nightly = []

[dev-dependencies]
rand = "0.*"
histogram = "0.*"
